const CategoryActionTypes = {
    LIST_CATEGORIES :           'LIST_CATEGORIES',
    LIST_CATEGORIES_SUCCESS :   'LIST_CATEGORIES_SUCCESS',
    LIST_CATEGORIES_FAILURE :   'LIST_CATEGORIES_FAILURE',
    CREATE_CATEGORIES :         'CREATE_CATEGORIES',
    CREATE_CATEGORIES_SUCCESS : 'CREATE_CATEGORIES_SUCCESS',
    CREATE_CATEGORIES_FAILURE : 'CREATE_CATEGORIES_FAILURE',
    EDIT_CATEGORIES :           'EDIT_CATEGORIES',
    EDIT_CATEGORIES_SUCCESS :   'EDIT_CATEGORIES_SUCCESS',
    EDIT_CATEGORIES_FAILURE :   'EDIT_CATEGORIES_FAILURE',
    DELETE_CATEGORIES :         'DELETE_CATEGORIES',
    DELETE_CATEGORIES_SUCCESS : 'DELETE_CATEGORIES_SUCCESS',
    DELETE_CATEGORIES_FAILURE : 'DELETE_CATEGORIES_FAILURE',
    SHOW_CATEGORY :             'SHOW_CATEGORY',
    SHOW_CATEGORY_SUCCESS :     'SHOW_CATEGORY_SUCCESS',
    SHOW_CATEGORY_FAILURE :     'SHOW_CATEGORY_FAILURE',
    HANDLE_CATEGORY_TITLE :     'HANDLE_CATEGORY_TITLE',
    SET_CATEGORY_DEFAULTS :     'SET_CATEGORY_DEFAULTS',
    LIST_ALL_CATEGORIES :       'LIST_ALL_CATEGORIES'    // this is different from LIST_CATEGORIES
};

export default CategoryActionTypes;


