const CommentActionTypes = {
    LIST_COMMENTS : 'LIST_COMMENTS',
    LIST_COMMENTS_SUCCESS : 'LIST_COMMENTS_SUCCESS',
    LIST_COMMENTS_FAILURE : 'LIST_COMMENTS_FAILURE',
    EDIT_COMMENTS : 'EDIT_COMMENTS',
    EDIT_COMMENTS_SUCCESS : 'EDIT_COMMENTS_SUCCESS',
    EDIT_COMMENTS_FAILURE : 'EDIT_COMMENTS_FAILURE',
    DELETE_COMMENTS : 'DELETE_COMMENTS',
    DELETE_COMMENTS_SUCCESS : 'DELETE_COMMENTS_SUCCESS',
    DELETE_COMMENTS_FAILURE : 'DELETE_COMMENTS_FAILURE',
};

export default CommentActionTypes;
