const PostActionTypes = {
    LIST_POSTS : 'LIST_POSTS',
    LIST_POSTS_SUCCESS : 'LIST_POSTS_SUCCESS',
    LIST_POSTS_FAILURE : 'LIST_POSTS_FAILURE',
    CREATE_POSTS : 'CREATE_POSTS',
    CREATE_POSTS_SUCCESS : 'CREATE_POSTS_SUCCESS',
    CREATE_POSTS_FAILURE : 'CREATE_POSTS_FAILURE',
    EDIT_POSTS : 'EDIT_POSTS',
    EDIT_POSTS_SUCCESS : 'EDIT_POSTS_SUCCESS',
    EDIT_POSTS_FAILURE : 'EDIT_POSTS_FAILURE',
    DELETE_POSTS : 'DELETE_POSTS',
    DELETE_POSTS_SUCCESS : 'DELETE_POSTS_SUCCESS',
    DELETE_POSTS_FAILURE : 'DELETE_POSTS_FAILURE',
    SHOW_POST : 'SHOW_POST',
    SHOW_POST_SUCCESS : 'SHOW_POST_SUCCESS',
    SHOW_POST_FAILURE : 'SHOW_POST_FAILURE',
    HANDLE_FIELD_CHANGE : 'HANDLE_FIELD_CHANGE',
    SET_POST_DEFAULTS : 'SET_POST_DEFAULTS',
    RESET_FIELDS : 'RESET_FIELDS',
};

export default PostActionTypes;
