const TagActionTypes = {
    LIST_TAGS : 'LIST_TAGS',
    LIST_TAGS_SUCCESS : 'LIST_TAGS_SUCCESS',
    LIST_TAGS_FAILURE : 'LIST_TAGS_FAILURE',
    CREATE_TAGS : 'CREATE_TAGS',
    CREATE_TAGS_SUCCESS : 'CREATE_TAGS_SUCCESS',
    CREATE_TAGS_FAILURE : 'CREATE_TAGS_FAILURE',
    EDIT_TAGS : 'EDIT_TAGS',
    EDIT_TAGS_SUCCESS : 'EDIT_TAGS_SUCCESS',
    EDIT_TAGS_FAILURE : 'EDIT_TAGS_FAILURE',
    DELETE_TAGS : 'DELETE_TAGS',
    DELETE_TAGS_SUCCESS : 'DELETE_TAGS_SUCCESS',
    DELETE_TAGS_FAILURE : 'DELETE_TAGS_FAILURE',
    SHOW_TAG : 'SHOW_TAG',
    SHOW_TAG_SUCCESS : 'SHOW_TAG_SUCCESS',
    SHOW_TAG_FAILURE : 'SHOW_TAG_FAILURE',
    HANDLE_TAG_TITLE : 'HANDLE_TAG_TITLE',
    SET_TAG_DEFAULTS : 'SET_TAG_DEFAULTS',
    LIST_ALL_TAGS : 'LIST_ALL_TAGS',
};

export default TagActionTypes;
