const UserActionTypes = {
    LIST_USERS : 'LIST_USERS',
    LIST_USERS_SUCCESS : 'LIST_USERS_SUCCESS',
    LIST_USERS_FAILURE : 'LIST_USERS_FAILURE',
    CREATE_USERS : 'CREATE_USERS',
    CREATE_USERS_SUCCESS : 'CREATE_USERS_SUCCESS',
    CREATE_USERS_FAILURE : 'CREATE_USERS_FAILURE',
    EDIT_USERS : 'EDIT_USERS',
    EDIT_USERS_SUCCESS : 'EDIT_USERS_SUCCESS',
    EDIT_USERS_FAILURE : 'EDIT_USERS_FAILURE',
    DELETE_USERS : 'DELETE_USERS',
    DELETE_USERS_SUCCESS : 'DELETE_USERS_SUCCESS',
    DELETE_USERS_FAILURE : 'DELETE_USERS_FAILURE',
    SHOW_USER : 'SHOW_USER',
    SHOW_USER_SUCCESS : 'SHOW_USER_SUCCESS',
    SHOW_USER_FAILURE : 'SHOW_USER_FAILURE',
    HANDLE_USER_CHANGE : 'HANDLE_USER_CHANGE',
    SET_USER_DEFAULTS : 'SET_USER_DEFAULTS',
    RESET_USER_FIELDS : 'RESET_USER_FIELDS',
};

export default UserActionTypes;
